version: 0.1.{build}

skip_tags: true

configuration: Release

install:
  - cinst opencover -source https://nuget.org/api/v2/
  - cinst coveralls.io -source https://nuget.org/api/v2/

branches:
  only:
  - master
  - develop

environment:
  COVERALLS_REPO_TOKEN:
    secure: vZbAIL9e5R5Gmz64+FtRItbI9H5bSOtQH300lUbo18AXVDMcOmvd/tD8lnBnthnR

before_build:
  - nuget restore src\CssSyntax.sln

build:
  project: src\CssSyntax.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"\"src\CssSyntax.Test\bin\Release\CssSyntax.Test.dll\" /logger:Appveyor" -skipautoprops -filter:"+[CssSyntax*]*" -output:coverage.xml
  - coveralls.net --opencover coverage.xml

artifacts:
  - path: coverage.xml